Shore/test
ComidasCenas/back-c-c pull request #17
Opened 2020-02-13 10:09 UTC by sarnaizgarcia

2020-02-13 12:21 UTC, ardiadrianadri requested changes

2020-02-13 12:21 UTC, ardiadrianadri commented on models/test_recipe_model.py
> +        self.assertEqual(
Aqui me falta una comprobación de que el db.session.add recibe una instancia del modelo de receta que, además, contiene los mismos valores que se usan para instanciar la clase RecipeModel

2020-02-13 12:21 UTC, ardiadrianadri commented on models/test_recipe_model.py
> +
Y estos comentarios??? 🤔 🤔 🤔 🤔 🤔 🤔 🤔 🤔

2020-02-13 12:21 UTC, ardiadrianadri commented on models/test_recipe_model.py
> +        self.assertEqual(mocked_first.call_count, 1)
Que bueno que hayas podido contabilizar las llamadas al método first sin tener que falsear el resultado de filter_by 👏 👏👏. Ya me contarás como lo has hecho

2020-02-13 12:21 UTC, ardiadrianadri commented on models/test_user_model.py
> +        # print('-----------------------------------------')
Me tienes que explicar esto....

2020-02-13 12:21 UTC, ardiadrianadri commented on models/test_user_model.py
> +        # print('-----------------------------------------')
Y esto.... 😑 😑😑😑😑😑😑

2020-02-18 09:55 UTC, sarnaizgarcia commented on models/test_recipe_model.py
> +
Cuando termine los tests de los modelos los borro. Palabrita!!

2020-02-18 09:57 UTC, sarnaizgarcia commented on models/test_recipe_model.py
> +        self.assertEqual(
No entiendo muy bien a qué te refieres con esto. Me lo puedes explicar con más detalle, por favor?

2020-02-19 10:19 UTC, ardiadrianadri approved these changes

2020-02-19 10:26 UTC, merged