Feature/loggin session
ComidasCenas/back-c-c pull request #9
Opened 2020-01-09 11:47 UTC by sarnaizgarcia

2020-01-09 12:02 UTC, ardiadrianadri requested changes
Hazme los cambios que te pido por ahora... luego me lo descargo y hago un poco de QA

2020-01-09 12:02 UTC, ardiadrianadri commented on models/user_model.py
> +        db.session.delete(self)
Estaría bien aquí crear un logger y lanzar un log de debug igual que en los anteriores métodos

2020-01-09 12:02 UTC, ardiadrianadri commented on requirements.txt
> +pkg-resources==0.0.0
Miedo me da esta linea... tengo entendido que se genera por un bug en la actual versión de Ubuntu... y esto hace que la instalación de dependencias fallen en el resto de sistemas operativos (https://stackoverflow.com/questions/39577984/what-is-pkg-resources-0-0-0-in-output-of-pip-freeze-command)

Borrarla

2020-01-09 12:02 UTC, ardiadrianadri commented on resources/user_resource.py
> +        return {'access_token': new_token}, 200
Veo una relación clara entre UserRegister y UserFinder que podría justificar que estén en el mismo fichero.

El Login lo veo cogido con pinzas.... y la clase para el refresco de token... 👎 ⛔️ 😱 🙀 😱 🙀 😱 🙀 😱 🙀 ⛔️👎

Mueve estas clases aun fichero auth_resurce.py mejor

2020-01-09 13:35 UTC, ardiadrianadri requested changes
Mas cambios para hacer... y, además, te voy a abrir algunas incidencias

2020-01-09 13:35 UTC, ardiadrianadri commented on requirements.txt
> +Flask-JWT-Extended==3.24.1
Flask-JWT es incompatible con una versión de la librería PyJWT superior a la 1.5. Flask-JWT-Extended es incompatible con una versión de la librería PyJWT inferior a la 1.6.

Visto esto... ¿Qué hacemos? Hay que tener cuidado con las incompatibilidades entre librerías porque nos pueden dar muchos problemas. En este caso el problema radica en que no puede existir un proyecto con las librerías Flask-JWT y Flask-JWT-Extended. Se tiene que elegir una. Como su nombre indica, la librería Flask-JWT-Extendend tiene la misma funcionalidad que Flask-JWT pero con mas cosas. Por lo tanto, en este caso, Flask-JWT sobra.

2020-01-09 13:35 UTC, ardiadrianadri commented on app.py
>  api.add_resource(UserRegister, '/register')
Vaya... este se me ha pasado. Pero ahora no cuela

No existe ningún contrato en el diseño de las API que haga referencia a register. Concretamente, nombrar una url como "register" va en contra de la definición de API REST porque es un verbo que hace referencia a una acción cuando, en REST, las url tiene que hacer referencia a una entidad. (Todas menos la de login)

La url correcta en este caso sería ```/user```

2020-01-09 13:35 UTC, ardiadrianadri commented on app.py
> +from resources.user_resource import UserRegister, UserFinder, UserLogin, TokenRefresh
Esta linea supera los 79 characters como marca el linter. Hay que hacerla más pequeña. Prueba en dividirla en 2:

```
from resources.user_resource import UserRegister, UserFinder
from resources.user_resource import UserLogin, TokenRefres
```

De todas formas... como la clase del login y del token va a otro fichero, con ese refactor, este problema se solventa

2020-01-09 13:35 UTC, ardiadrianadri commented on controllers/get_user_by_id.py
> +            raise UserNotFoundError
Yo creo que ya puestos ha hacer una funcionalidad, hacerla completa que no cuesta nada. Lo suyo sería que este controlador devolviera una respuesta que sea un error en caso de que la búsqueda por usuario falle y/o una entidad serializable "User" con los datos del usuario en caso de que encuentre un usuario. El mensaje "user found" esta bien pero es claramente insuficiente.

2020-01-11 20:39 UTC, sarnaizgarcia commented on models/user_model.py
> +        db.session.delete(self)
Hecho.

2020-01-11 21:08 UTC, sarnaizgarcia commented on requirements.txt
> +pkg-resources==0.0.0
Borrada

2020-01-11 21:09 UTC, sarnaizgarcia commented on resources/user_resource.py
> +        return {'access_token': new_token}, 200
Movidas

2020-01-11 21:09 UTC, sarnaizgarcia commented on models/user_model.py
> +        db.session.delete(self)
Creado

2020-01-11 21:09 UTC, sarnaizgarcia commented on requirements.txt
> +Flask-JWT-Extended==3.24.1
Pensé que había eliminado del todo Flask-JWT. Lo quito

2020-01-11 21:17 UTC, sarnaizgarcia commented on app.py
>  api.add_resource(UserRegister, '/register')
Cambiado

2020-01-11 21:18 UTC, sarnaizgarcia commented on app.py
> +from resources.user_resource import UserRegister, UserFinder, UserLogin, TokenRefresh
Solucionado

2020-01-13 09:36 UTC, merged